#!/usr/bin/env bash
# Validates that the committed openapi.json matches the spec generated by
# control-api. Fails the build if they diverge or if the spec is invalid.
set -euo pipefail

COMMITTED="openapi.json"
GENERATED="$(mktemp)"
trap 'rm -f "$GENERATED"' EXIT

echo "openapi-sync: building control-api..."
cargo build -p control-api --quiet

echo "openapi-sync: generating fresh OpenAPI spec..."
./target/debug/control-api print-openapi > "$GENERATED"

# Validate the generated spec is parseable JSON with OpenAPI 3.x header.
OPENAPI_VER=$(python3 -c "
import json, sys
data = json.load(open('$GENERATED'))
ver = data.get('openapi', '')
if not ver.startswith('3.'):
    print(f'ERROR: openapi field is {ver!r}, expected 3.x', file=sys.stderr)
    sys.exit(1)
print(ver)
")
echo "openapi-sync: spec version is $OPENAPI_VER — valid OpenAPI 3.x"

# If committed spec exists, check it matches the generated one.
if [[ -f "$COMMITTED" ]]; then
    if ! diff -u "$COMMITTED" "$GENERATED" > /dev/null 2>&1; then
        echo "ERROR: openapi.json is out of sync with control-api handlers."
        echo "       Run: cargo run -p control-api -- print-openapi > openapi.json"
        echo ""
        diff -u "$COMMITTED" "$GENERATED" || true
        exit 1
    fi
    echo "openapi-sync: openapi.json is in sync ✓"
else
    echo "openapi-sync: no committed openapi.json found — generating initial file."
    cp "$GENERATED" "$COMMITTED"
    echo "openapi-sync: wrote openapi.json — commit it to the repo."
    # Do not fail; the CI job that first introduces the file will commit it.
fi
